import fs from "fs";
import path from "path";

import type { Widget, WidgetRegistry } from "./types";

import createLogger from "utils/logger";

// A built-in plugin entry from the generated barrel (src/widgets/plugins-generated.ts).
// `widget` is unknown because it is validated by isValidWidget before use.
export interface BuiltinPlugin {
  dir: string;
  widget: unknown;
}

const logger = createLogger("pluginLoader");

function isValidWidget(obj: unknown, dirName: string): obj is Widget {
  if (!obj || typeof obj !== "object") {
    logger.error("Plugin '%s': export is not an object", dirName);
    return false;
  }

  const w = obj as Record<string, unknown>;

  if (typeof w.id !== "string" || w.id.length === 0) {
    logger.error("Plugin '%s': missing or invalid 'id' (must be a non-empty string)", dirName);
    return false;
  }

  if (w.id !== dirName) {
    logger.error("Plugin '%s': id '%s' does not match directory name", dirName, w.id);
    return false;
  }

  if (typeof w.name !== "string" || w.name.length === 0) {
    logger.error("Plugin '%s': missing or invalid 'name' (must be a non-empty string)", dirName);
    return false;
  }

  if (!w.definition || typeof w.definition !== "object") {
    logger.error("Plugin '%s': missing or invalid 'definition' (must be an object)", dirName);
    return false;
  }

  const def = w.definition as Record<string, unknown>;
  if (typeof def.api !== "string" && typeof def.proxyHandler !== "function") {
    logger.error("Plugin '%s': definition must have an 'api' string or a 'proxyHandler' function", dirName);
    return false;
  }

  return true;
}

function registerWidget(widget: Widget, registry: WidgetRegistry, seen: Set<string>): void {
  if (seen.has(widget.id)) {
    logger.warn("Plugin '%s': id already registered, skipping", widget.id);
    return;
  }

  registry[widget.id] = widget.definition;
  seen.add(widget.id);
  logger.debug("Loaded plugin: %s", widget.id);

  if (widget.aliases) {
    for (const alias of widget.aliases) {
      if (seen.has(alias)) {
        logger.warn("Plugin '%s': alias '%s' conflicts with existing widget, skipping alias", widget.id, alias);
        continue;
      }
      registry[alias] = widget.definition;
      seen.add(alias);
      logger.debug("Registered alias: %s -> %s", alias, widget.id);
    }
  }
}

// Built-in plugins (src/widgets/plugins/<name>/index.ts) are passed in from the static
// barrel generated by scripts/generate-plugin-barrel.mjs, imported by widgets.js. They are
// imported statically (not via require.context) because webpack treats them as async modules
// (they import proxy handlers), and require.context returns Promises for async modules, which
// this synchronous loader cannot consume. widgets.js (not this module) imports the barrel so
// plugin-loader stays free of the plugins -> generic -> widgets -> plugin-loader import cycle.
function loadBuiltinPlugins(builtin: BuiltinPlugin[], registry: WidgetRegistry, seen: Set<string>): void {
  for (const { dir, widget } of builtin) {
    // widget can be transiently undefined under import cycles (a plugin's own unit test
    // imports it as the entry module); skip silently -- production loads them fully.
    if (!widget) continue;
    if (isValidWidget(widget, dir)) {
      registerWidget(widget, registry, seen);
    }
  }
}

// External plugins live in HOMEPAGE_PLUGINS_DIR and are loaded at runtime, so webpack can
// never bundle them. They ship plain CommonJS (index.js/.cjs) loaded via the real Node
// require below (native require cannot load .ts).
function loadExternalPlugins(dir: string, registry: WidgetRegistry, seen: Set<string>): void {
  if (!fs.existsSync(dir)) {
    return;
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    logger.error("Failed to read plugins directory '%s': %s", dir, err);
    return;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const dirName = entry.name;
    const pluginDir = path.join(dir, dirName);

    let mod: { default?: unknown };
    try {
      // __non_webpack_require__ is webpack's escape hatch to the real Node require, so
      // webpack does not try to bundle this arbitrary runtime path. In tests it is provided
      // by vitest.setup.js (createRequire). External plugins ship CommonJS (index.js/.cjs);
      // native require cannot load .ts.
      mod = __non_webpack_require__(pluginDir);
    } catch (err) {
      logger.error("Plugin '%s': failed to load: %s", dirName, err);
      continue;
    }

    const widget = mod.default ?? mod;

    if (isValidWidget(widget, dirName)) {
      registerWidget(widget, registry, seen);
    }
  }
}

let cachedDefinitions: WidgetRegistry | null = null;

export function getPluginDefinitions(builtinPlugins: BuiltinPlugin[], legacyKeys?: Set<string>): WidgetRegistry {
  if (cachedDefinitions) return cachedDefinitions;

  const registry: WidgetRegistry = {};
  const seen = new Set<string>(legacyKeys ?? []);

  loadBuiltinPlugins(builtinPlugins, registry, seen);

  const externalDir = process.env.HOMEPAGE_PLUGINS_DIR;
  if (externalDir) {
    loadExternalPlugins(externalDir, registry, seen);
  }

  cachedDefinitions = registry;
  return registry;
}

export function clearPluginCache(): void {
  cachedDefinitions = null;
}
