// AUTO-GENERATED by scripts/generate-plugin-barrel.mjs -- do not edit by hand.
// Built-in widget plugins, imported statically so their definitions resolve
// synchronously (require.context returns Promises for these async modules).
import adguard from "./plugins/adguard";
import sonarr from "./plugins/sonarr";
import uptimekuma from "./plugins/uptimekuma";

const builtinPlugins: { dir: string; widget: unknown }[] = [
  { dir: "adguard", widget: adguard },
  { dir: "sonarr", widget: sonarr },
  { dir: "uptimekuma", widget: uptimekuma },
];

export default builtinPlugins;
