name: Docs

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:

  test:
    name: Test Build Docs
    if: github.repository == 'gethomepage/homepage' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v8
      - run: sudo apt-get install pngquant
      - name: Test Docs Build
        run: uv run --frozen zensical build --clean

  build-docs:
    name: Build Docs
    if: github.repository == 'gethomepage/homepage' && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v8
      - run: sudo apt-get install pngquant
      - name: Build Docs
        run: uv run --frozen zensical build --clean
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site

  deploy:
    name: Deploy Docs
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/deploy-pages@v5
        id: deployment
